---
- name: Set Ansible Python interpreter to Kolla venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ manila_kolla_venv }}/bin/python"

- name: Download Manila image
  ansible.builtin.get_url:
    url: https://tarballs.opendev.org/openstack/manila-image-elements/images/manila-service-image-master.qcow2
    dest: /root/manila-service-image.qcow2
    mode: 640
  notify: create_default_share_type
