---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m
  chart:
    spec:
      version: "1.12.x"
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  values:
    image:
      tag: v0.11.0  # Newer versions not working properly with OpenStack Designate
    provider: designate
    policy: sync
    sources:
      - service
      - ingress
    domainFilters:
      - ${DOMAIN}
    env:
      - name: OS_AUTH_URL
        value: http://192.168.1.11:5000/v3
      - name: OS_AUTH_TYPE
        value: v3applicationcredential
      - name: OS_APPLICATION_CREDENTIAL_ID
        value: ${DESIGNATE_AUTH_ID}
      - name: OS_APPLICATION_CREDENTIAL_SECRET
        value: ${DESIGNATE_AUTH_SECRET}
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
