---
- name: Configure storage for Cinder
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - cinder.yml
    - cinder_backup.yml
  listen: configure_cinder

- name: Configure storage for Glance
  ansible.builtin.include_tasks: glance.yml
  listen: configure_glance

- name: Configure storage for Manila
  ansible.builtin.include_tasks: manila.yml
  listen: configure_manila

- name: Configure storage for RadosGW
  ansible.builtin.include_tasks: radosgw.yml
  listen: configure_radosgw
