---
- name: Create the config override directory
  ansible.builtin.file:
    path: "{{ nova_kolla_config_dir }}"
    state: directory
    mode: '0750'

- name: Template the 'nova-compute.conf' override file
  ansible.builtin.template:
    src: nova-compute.conf.j2
    dest: "{{ nova_kolla_config_dir }}/nova-compute.conf"
    mode: '0640'
  notify: restart_nova_compute

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
