---
- name: Create (or recreate) the container
  community.docker.docker_container:
    name: gitlab-runner
    image: docker.io/gitlab/gitlab-runner:latest
    restart_policy: always
    recreate: true
    user: 9999:{{ docker_group.gid }}
    network_mode: host
    volumes:
      # I'm aware of how stupid this is. Blame GitLab for being unable to
      #  stick to a single directory for runner config.
      - /etc/gitlab-runner:/.gitlab-runner
      - /etc/gitlab-runner:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  listen: recreate_container
