---
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH           # Run on main branch commits
    - if: $CI_COMMIT_TAG                                    # Run on tags
    - if: $CI_PIPELINE_SOURCE == "schedule"                 # Run when scheduled
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"      # Run for merge requests
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS      # No duplicate pipelines for merge requests
      when: never

default:
  tags:
    - homelab
  interruptible: true

stages:
  - validate
  - build
  - renovate

include:
  - local: '/.gitlab/ci/docs.yml'
  - local: '/.gitlab/ci/kubernetes.yml'
  - local: '/.gitlab/ci/metal.yml'
  - local: '/.gitlab/ci/renovate.yml'
