---
# Default state for all rules
default: true

# MD007/ul-indent : Unordered list indentation : https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md007.md
MD007:
  # Spaces for indent
  indent: 4

MD033:
  allowed_elements: ["br"]
