---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: vault
  interval: 60m
  path: ./cluster/platform/external-secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
