---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  dependsOn:
    - name: csi-cinder
  interval: 60m
  path: ./cluster/platform/postgres
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
