---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  dependsOn:
    - name: trust-manager
    - name: csi-cinder
  interval: 60m
  path: ./cluster/platform/vault
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
