---
- name: Partition the block devices
  community.general.parted:
    device: "{{ swift_device }}"
    label: gpt
    number: 1
    name: KOLLA_SWIFT_DATA
    state: present
  loop: "{{ swift_devices }}"
  loop_control:
    loop_var: swift_device
  register: swift_partitions
  notify: generate_rings

- name: Create the filesystems
  community.general.filesystem:
    fstype: xfs
    dev: "{{ swift_partition.disk.dev }}1"
    opts: "-L d{{ swift_device_index }}"
    state: present
  loop: "{{ swift_partitions.results }}"
  loop_control:
    loop_var: swift_partition
    index_var: swift_device_index
  notify: generate_rings

- name: Stat the ring files
  ansible.builtin.stat:
    path: "/etc/kolla/config/swift/{{ ring_file }}"
  loop:
    - account.builder
    - account.ring.gz
    - container.builder
    - container.ring.gz
    - object.builder
    - object.ring.gz
  loop_control:
    loop_var: ring_file
  register: ring_files

- name: Assert that ring files are present
  ansible.builtin.assert:
    that: ring_file.stat.exists
    quiet: true
  changed_when: not ring_file.stat.exists
  failed_when: false
  loop: "{{ ring_files.results }}"
  loop_control:
    loop_var: ring_file
  notify: generate_rings

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
