---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
spec:
  interval: 120m
  url: https://charts.gitlab.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
spec:
  interval: 5m
  chart:
    spec:
      version: "0.86.0"
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true

    metrics:
      enabled: true
      podMonitor:
        enabled: true  # PodMonitor is the preferred method for GitLab Runner metrics

    runners:
      secret: gitlab-runner
    extraObjects:
      - apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: gitlab-runner
        spec:
          refreshInterval: 1h
          secretStoreRef:
            kind: ClusterSecretStore
            name: gitlab
          target:
            template:
              data:
                runner-registration-token: "" # need to leave as an empty string for compatibility reasons
                runner-token: "{{`{{ .runnerToken }}`}}"
          data:
            - secretKey: runnerToken
              remoteRef:
                key: GITLAB_RUNNER_TOKEN
