---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
configMapGenerator:
  - name: custom-branding
    files:
      - files/EmailLogo.png
  - name: email-templates
    files:
      - files/base.html
generatorOptions:
  disableNameSuffixHash: true
