---
- name: Download pre-built Amphora image
  ansible.builtin.get_url:
    url: "{{ octavia_amphora_image_url }}"
    dest: /root/amphora-x64-haproxy.qcow2
    mode: 0640

- name: 'Octavia : Source user credentials'
  ansible.builtin.shell:
    cmd: source /etc/kolla/octavia-openrc.sh

- name: 'Octavia : Get user password'
  ansible.builtin.shell:
    cmd: |
      grep OS_PASSWORD /etc/kolla/octavia-openrc.sh | awk '{
        res=$2
        split(res,resArr,"=")
        print resArr[2]
      }' | sed s/\'//g
  register: octavia_password

- name: 'Octavia : Upload the Amphora image'
  openstack.cloud.image:
    auth:
      auth_url: http://{{ ansible_default_ipv4.address }}:5000
      username: octavia
      password: "{{ octavia_password.stdout }}"
      project_name: service
      user_domain_name: Default
      project_domain_name: Default
    name: amphora-x64-haproxy
    container_format: bare
    disk_format: qcow2
    visibility: private
    tags:
      - amphora
    filename: /root/amphora-x64-haproxy.qcow2
    state: present
    properties:
      hw_architecture: x86_64
      hw_rng_model: virtio

- name: Remove pre-built image file
  ansible.builtin.file:
    path: /root/amphora-x64-haproxy.qcow2
    state: absent
