---
- name: Set Python interpreter to Kolla venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ kolla_venv }}/bin/python"

- name: Check if an Amphora image already exists in Glance
  openstack.cloud.image_info:
    name: amphora-x64-haproxy
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
  register: amphora_images

- name: Include Amphora image tasks
  ansible.builtin.include_tasks: amphora-image.yml
  when: amphora_images.images | length == 0

- name: "Fix 'octavia-interface.service'"
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/octavia-interface.service
    regexp: 'sleep'
    line: 'ExecStartPre=/usr/bin/sleep 15'
    insertbefore: '^ExecStartPre=/sbin/ip'

- name: "Enable Cinder volume driver"
  ansible.builtin.lineinfile:
    path: /etc/kolla/octavia-worker/octavia.conf
    insertafter: '^compute_driver'
    regexp: '^volume_driver ='
    line: "volume_driver = volume_cinder_driver"
  notify: restart_octavia_worker

- name: "Configure Cinder volume driver"
  ansible.builtin.blockinfile:
    path: /etc/kolla/octavia-worker/octavia.conf
    insertafter: "EOF"
    prepend_newline: true
    block: |
      [cinder]
      region_name = RegionOne
      endpoint_type = internal
      ca_certificates_file =
      volume_type = PREMIUM
      volume_size = 5
  notify: restart_octavia_worker
