---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab
  target:
    name: ${APP}-volsync-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        RESTIC_PASSWORD: "{{ .REPOSITORY_PASSWORD }}"
        RESTIC_REPOSITORY: "s3:${BACKUPS__S3_ENDPOINT}/${BACKUPS__S3_BUCKET}/volumes/${APP}"
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_KEY }}"
  data:
    - secretKey: REPOSITORY_PASSWORD
      remoteRef:
        key: BACKUPS__REPO_PASSWORD

    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: BACKUPS__S3_ACCESS_KEY

    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: BACKUPS__S3_SECRET_KEY
