---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media-pvc.yaml
configMapGenerator:
  - name: media-grafana-dashboard
    files:
      - dashboards/media.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: media-server
        app.kubernetes.io/component: monitoring
