---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled  # Prevent accidental deletion
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: general-shared
  resources:
    requests:
      storage: 2Ti
