---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
spec:
  interval: 5m
  chart:
    spec:
      version: "4.x"
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kubereboot
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/kubereboot/charts/blob/main/charts/kured/values.yaml
  values:
    configuration:
      annotateNodes: true
      # Uncomment for RHEL-based systems
      rebootSentinelCommand: sh -c "! needs-restarting --reboothint"
      # TODO: Integrate with Prometheus alerting
      # prometheusUrl: "http://prometheus.monitoring"
      # alertFilterRegexp: "^RebootRequired$"
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 25m
        memory: 100Mi
