---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-secrets
  namespace: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: jellyfin-secrets
    creationPolicy: Owner
  # Vault secret object
  data:
    - secretKey: jellyfin-server-id
      remoteRef:
        key: /mediasrv/jellyfin
        property: serverID
    - secretKey: ldap-bind-password
      remoteRef:
        key: /mediasrv/jellyfin
        property: ldapServiceAccountPassword
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-restic-config
type: Opaque
stringData:
  RESTIC_REPOSITORY: gs:${GCP_BACKUP_BUCKET_NAME}:/volsync/jellyfin
  RESTIC_PASSWORD: ${BACKUP_REPO_PASSWORD}
  GOOGLE_PROJECT_ID: ${GCP_BACKUP_PROJECT_ID}
data:
  # This value is base64 encoded by default
  GOOGLE_APPLICATION_CREDENTIALS: ${GCP_BACKUP_BUCKET_CREDS}
