---
- name: Generate '/etc/kolla/clouds.yaml'
  ansible.builtin.shell: |
    source {{ kolla_venv }}/bin/activate
    kolla-ansible post-deploy

- name: Fetch 'clouds.yaml' as an output
  ansible.builtin.fetch:
    src: /etc/kolla/clouds.yaml
    dest: "{% if ci_pipeline == 'true' %}{{ playbook_dir }}/tests/output/{% else %}{{ playbook_dir }}/output/{% endif %}"
    flat: true

- name: Assert shell configuration in '.bash_profile'
  ansible.builtin.blockinfile:
    path: /root/.bash_profile
    prepend_newline: true
    block: |
      source {{ kolla_venv }}/bin/activate
      source /etc/kolla/admin-openrc.sh

- name: Set Python interpreter to venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ kolla_venv }}/bin/python"

- name: Create 'admin' SSH public key
  openstack.cloud.keypair:
    name: admin
    public_key: "{{ lookup('file', common.ssh_pubkey_file | mandatory) }}"
    state: present
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
