---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secrets
  namespace: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: prowlarr-secrets
    creationPolicy: Owner
  # Vault secret object(s)
  data:
    - secretKey: apiKey
      remoteRef:
        key: /mediasrv/prowlarr
        property: apiKey
