---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  annotations:
    lbipam.cilium.io/ips: 10.0.40.5
  labels:
    io.cilium.gateway/owning-gateway: public
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
    - name: mosquitto-http
      port: 1883
      protocol: TCP
      targetPort: mosquitto-http
