---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secrets
stringData:
  mosquitto.passwd: mqtt:$7$101$zsFbkdZ74f/cg8hP$gNgtoa1feoypjC18ocXjx3C2TEO4s7xGYXkdF2PoUakhylHVJBOHgvC+x3W5bhEjs7gm4vnmJJElSnESkP5zxA==
