---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-backup-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab
  target:
    name: talos-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: AGE_PUBLIC_KEY
      remoteRef:
        key: BACKUPS__ETCD_PUBKEY

    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: BACKUPS__S3_ACCESS_KEY

    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: BACKUPS__S3_SECRET_KEY
