---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab
  target:
    name: alertmanager-credentials
    creationPolicy: Owner
  data:
    - secretKey: healthcheck_url
      remoteRef:
        key: HEALTHCHECK_URL

    - secretKey: pushover_user_key
      remoteRef:
        key: PUSHOVER_USER_KEY

    - secretKey: pushover_token
      remoteRef:
        key: PUSHOVER_TOKEN
