---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-secrets
  namespace: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: sabnzbd-secrets
    creationPolicy: Owner
  # Vault secret object
  data:
    - secretKey: apiKey
      remoteRef:
        key: /mediasrv/sabnzbd
        property: apiKey
    - secretKey: nzbKey
      remoteRef:
        key: /mediasrv/sabnzbd
        property: nzbKey
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-restic-config
type: Opaque
stringData:
  RESTIC_REPOSITORY: gs:${GCP_BACKUP_BUCKET_NAME}:/volsync/sabnzbd
  RESTIC_PASSWORD: ${BACKUP_REPO_PASSWORD}
  GOOGLE_PROJECT_ID: ${GCP_BACKUP_PROJECT_ID}
data:
  # This value is base64 encoded by default
  GOOGLE_APPLICATION_CREDENTIALS: ${GCP_BACKUP_BUCKET_CREDS}
