---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 389ds-secrets
  namespace: 389ds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: 389ds-secrets
    creationPolicy: Owner
  # Vault secret object
  data:
    - secretKey: jellyfin-service-password
      remoteRef:
        key: /mediasrv/jellyfin
        property: ldapServiceAccountPassword
