---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 120m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      version: "v1.19.2"
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  values:
    crds:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  chart:
    spec:
      version: "v0.20.3"
      chart: trust-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
