---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 120m
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-designate-credentials
  namespace: external-dns
stringData:
  clouds.yaml: |
    ---
    clouds:
      openstack:
        auth:
          auth_url: "${OPENSTACK_AUTH_URL}"
          application_credential_id: "${DESIGNATE_AUTH_ID}"
          application_credential_secret: "${DESIGNATE_AUTH_SECRET}"
        region_name: "RegionOne"
        interface: "public"
        auth_type: "v3applicationcredential"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      version: "1.19.0"
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  values:
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/inovex/external-dns-openstack-webhook
          tag: 1.1.0
        extraVolumeMounts:
          - name: oscloudsyaml
            mountPath: /etc/openstack/
        resources: {}
    extraVolumes:
      - name: oscloudsyaml
        secret:
          secretName: openstack-designate-credentials
    policy: sync
    sources:
      - ingress
    domainFilters:
      - ${DOMAIN}
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
