---
apiVersion: v1
kind: Namespace
metadata:
  name: volsync
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backube
  namespace: volsync
spec:
  interval: 120m
  url: https://backube.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync
spec:
  interval: 5m
  chart:
    spec:
      version: "0.13.1"
      chart: volsync
      sourceRef:
        kind: HelmRepository
        name: backube
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/backube/volsync/blob/main/helm/volsync/values.yaml
  values: {}
