---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-pgbackrest
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab
  target:
    name: ${APP}-pgbackrest-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        s3.conf: |
          [global]
          repo1-cipher-pass = {{ .REPOSITORY_PASSWORD }}
          repo1-s3-key = {{ .S3_ACCESS_KEY }}
          repo1-s3-key-secret = {{ .S3_SECRET_KEY }}
  data:
    - secretKey: REPOSITORY_PASSWORD
      remoteRef:
        key: BACKUPS__REPO_PASSWORD

    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: BACKUPS__S3_ACCESS_KEY

    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: BACKUPS__S3_SECRET_KEY
