---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../workloads/platform/crunchy-pgo/sync.yaml
  - ../../../workloads/platform/gitlab-runner/sync.yaml
  - ../../../workloads/platform/volsync/sync.yaml
  - ../../../workloads/platform/vault/sync.yaml
