---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-standard
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-standard
  namespace: ceph-standard
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
    namespace: rook-ceph
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml
  values:
    configOverride: |
      [global]
      osd_pool_default_size = 2
      osd_pool_default_min_size = 1
      # newline to prevent parse error (rook bug?)
    toolbox:
      enabled: true
    monitoring:
      enabled: true
      metricsDisabled: false
      createPrometheusRules: true
      prometheusRuleOverrides:
        CephPGImbalance:
          disabled: true  # Causing noise due to my oddly-sized disks
      rulesNamespaceOverride:
      prometheusRule:
        labels:
          release: kube-prometheus-stack

    cephClusterSpec:
      dataDirHostPath: /var/mnt/rook/standard
      mon:
        count: 1
      mgr:
        count: 1
        modules:
          - name: pg_autoscaler
            enabled: true
          - name: dashboard
            enabled: false
          - name: nfs
            enabled: false
      dashboard:
        enabled: false
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
          - name: talos-aio  # Must match the node's hostname
            devices:
              # Device paths map to the SAS controller's drive bays.
              # We specify all 8 bays and can hotswap drives as needed.
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy1-lun-0
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy2-lun-0
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy3-lun-0
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy4-lun-0
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy5-lun-0
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy6-lun-0
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy7-lun-0
              - name: /dev/disk/by-path/pci-0000:08:00.0-sas-phy8-lun-0
      resources:
        osd:  # Tone down the default OSD requests
          requests:
            cpu: 500m
            memory: 1Gi

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: osd
          replicated:
            size: 2
        storageClass:
          enabled: true
          name: general-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            imageFormat: "2"
            imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-publish-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4  # ext4 is the recommended filesystem
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: general-block
      isDefault: true
      deletionPolicy: Delete

    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            failureDomain: osd
            replicated:
              size: 2
          dataPools:
            - failureDomain: osd
              replicated:
                size: 2
              name: data0
          metadataServer:
            activeCount: 1
            activeStandby: false
            priorityClassName: system-cluster-critical
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
        storageClass:
          enabled: true
          isDefault: false
          name: general-shared
          pool: data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-publish-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-publish-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4  # ext4 is the recommended filesystem
    cephFileSystemVolumeSnapshotClass:
      enabled: true
      name: general-shared
      isDefault: false
      deletionPolicy: Delete

    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: osd
            replicated:
              size: 2
          dataPool:
            failureDomain: osd
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
            parameters:
              bulk: "true"
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              requests:
                cpu: "1000m"
                memory: "1Gi"
              limits:
                memory: "2Gi"
            instances: 1
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          name: general-bucket
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          parameters:
            region: us-east-1
        route:
          # Enable an ingress for the ceph-objectstore
          enabled: false
          # The ingress port by default will be the object store's "securePort" (if set), or the gateway "port".
          # To override those defaults, set this ingress port to the desired port.
          # port: 80
          # annotations: {}
          # host:
          #   name: objectstore.example.com
          #   path: /
          #   pathType: PathPrefix
          # parentRefs:
          #   - name: internal
          #     namespace: kube-system
          #     sectionName: https
---
# Overrides size and failureDomain for builtin .mgr pool, since Rook Ceph
#  doesn't provide any way to configure this in the Helm chart directly.
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: builtin-mgr
  namespace: ceph-standard # namespace:cluster
spec:
  name: .mgr
  enableCrushUpdates: true  # Required to update failureDomain
  failureDomain: osd
  replicated:
    size: 2
    requireSafeReplicaSize: false
