---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificates.yaml
  - private-lb.yaml
  - public-lb.yaml
  - private-gateway.yaml
  - public-gateway.yaml
  - http-redirect.yaml
