---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: csi-cinder
  namespace: flux-system
spec:
  interval: 60m
  path: ./cluster/system/csi-cinder
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
