---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: descheduler
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 60m
  path: ./cluster/system/descheduler
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
