---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: kube-prometheus-stack
  interval: 60m
  path: ./cluster/system/external-dns
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      DOMAIN: ${DOMAIN}
      DESIGNATE_AUTH_ID: ${DESIGNATE_AUTH_ID}
      DESIGNATE_AUTH_SECRET: ${DESIGNATE_AUTH_SECRET}
