---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 60m
  path: ./cluster/system/monitoring/kube-prometheus-stack
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 60m
  path: ./cluster/system/monitoring/loki-stack
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 60m
  path: ./cluster/system/monitoring/flux-monitoring
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
