---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 60m
  path: ./cluster/system/trust-manager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
