---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 60m
  path: ./cluster/system/volsync
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
