---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 120m
  type: oci
  url: oci://ghcr.io/bank-vaults/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      version: "1.23.0"
      chart: vault-operator
      sourceRef:
        kind: HelmRepository
        name: vault-operator
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/bank-vaults/vault-operator/blob/main/deploy/charts/vault-operator/values.yaml
  values: {}
