---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 120m
  type: oci
  url: oci://ghcr.io/cloudnative-pg/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 5m
  chart:
    spec:
      version: "0.28.2"
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
