source "proxmox-clone" "k3s-master" {
  // Proxmox Builder Settings
  proxmox_url              = "${var.pve_host}"
  username                 = "${var.pve_api_token_id}"
  token                    = "${var.pve_api_token_secret}"
  node                     = "pve1"
  insecure_skip_tls_verify = var.pve_tlsInsecure
  task_timeout             = "10m"

  // SSH Communicator Settings
  ssh_username = "rocky"

  // VM Settings
  clone_vm             = "template-rocky8-base"
  vm_name              = "packer-rocky8-k3s-master"
  vm_id                = 9996
  template_name        = "template-rocky8-k3s-master"
  template_description = <<-EOT
    K3s Master Node template (Rocky Linux 8).

    Generated by Packer on ${timestamp()}.
  EOT

  memory     = 2048
  cores      = 1
  sockets    = 1
  os         = "l26"
  qemu_agent = true

  network_adapters {
    bridge   = "vmbr0"
    model    = "virtio"
    firewall = true
  }
}

source "proxmox-clone" "k3s-worker" {
  // Proxmox Builder Settings
  proxmox_url              = "${var.pve_host}"
  username                 = "${var.pve_api_token_id}"
  token                    = "${var.pve_api_token_secret}"
  node                     = "pve1"
  insecure_skip_tls_verify = var.pve_tlsInsecure
  task_timeout             = "10m"

  // SSH Communicator Settings
  ssh_username = "rocky"

  // VM Settings
  clone_vm             = "template-rocky8-base"
  vm_name              = "packer-rocky8-k3s-worker"
  vm_id                = 9995
  template_name        = "template-rocky8-k3s-worker"
  template_description = <<-EOT
    K3s Worker Node template (Rocky Linux 8).

    Generated by Packer on ${timestamp()}.
  EOT

  memory     = 2048
  cores      = 1
  sockets    = 1
  os         = "l26"
  qemu_agent = true

  network_adapters {
    bridge   = "vmbr0"
    model    = "virtio"
    firewall = true
  }
}

build {
  sources = [ "source.proxmox-clone.k3s-master", "source.proxmox-clone.k3s-worker" ]

  provisioner "shell" {
    inline = [
      "while [ ! -f /var/lib/cloud/instance/boot-finished ] ; do echo 'Waiting for cloud-init...' ; sleep 5 ; done"
    ]
  }

  provisioner "ansible" {
    playbook_file = "./templates/provisioning/k3s-cluster.yml"
    user          = "rocky"
    groups        = [ "k3s_cluster" ]
    use_proxy     = false    // Workaround for insecure rsa-sha1 algo
  }
}
