---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-release
spec:
  interval: 120m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      version: "1.18.7"
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-release
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml
  values: {}
