---
- name: Stat the default FCOS image
  openstack.cloud.image_info:
    image: "{{ openstack_fcos_image_name }}"
    filters:
      os_distro: fedora-coreos
      os_version: "{{ openstack_fcos_image_version | string }}"
      visibility: public
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
  register: coe_images

- name: Stat the public network
  openstack.cloud.networks_info:
    name: "{{ external_networks.networks[1].name }}"
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
  register: coe_public_networks

- name: Stat the default medium-size flavor
  openstack.cloud.compute_flavor_info:
    name: m1.medium
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
  register: coe_flavors

- name: "Magnum : Create 'Kubernetes v1.26' template"
  openstack.cloud.coe_cluster_template:
    name: Kubernetes v1.26-1
    image_id: "{{ coe_images.images[0].id }}"
    coe: kubernetes
    docker_storage_driver: overlay2
    docker_volume_size: 40
    volume_driver: cinder
    network_driver: flannel
    server_type: vm
    master_flavor_id: "{{ coe_flavors.flavors[0].id }}"
    flavor_id: "{{ coe_flavors.flavors[0].id }}"
    is_master_lb_enabled: false
    is_floating_ip_enabled: true
    external_network_id: "{{ coe_public_networks.networks[0].id }}"
    labels:
      # Node Options
      boot_volume_size: 10
      boot_volume_type: PREMIUM
      docker_volume_type: PREMIUM
      etcd_volume_size: 10
      etcd_volume_type: PREMIUM
      hw_cpu_mode: host-passthrough
      # Kubernetes Core Components
      kube_tag: v1.26.8-rancher1
      flannel_tag: v0.15.1  # Magnum pulls from outdated repo
      container_runtime: containerd
      containerd_version: 1.6.20
      containerd_tarball_sha256: 1d86b534c7bba51b78a7eeb1b67dd2ac6c0edeb01c034cc5f590d5ccd824b416
      coredns_tag: 1.10.1
      # OpenStack Cloud / CSI Components
      autoscaler_tag: v1.26.4
      cloud_provider_tag: v1.26.4
      cinder_csi_plugin_tag: v1.26.4
      k8s_keystone_auth_tag: v1.26.4
      magnum_auto_healer_tag: v1.26.4
      csi_attacher_tag: v4.2.0
      csi_provisioner_tag: v3.4.1
      csi_snapshotter_tag: v6.2.1
      csi_resizer_tag: v1.7.0
      csi_node_driver_registrar_tag: v2.8.0
      auto_healing_controller: magnum-auto-healer
      keystone_auth_enabled: true
      kube_dashboard_enabled: false
    is_public: true
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
