---
# Run all / only tasks that use Ansible OpenStack modules after this
- name: Set Python interpreter to venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ kolla_venv }}/bin/python"

- name: Include tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - networks.yml
    - flavors.yml

- name: Check if the default CoreOS image exists in Glance
  openstack.cloud.image_info:
    image: "{{ openstack_fcos_image_name }}"
    filters:
      os_distro: fedora-coreos
      os_version: "{{ openstack_fcos_image_version | string }}"
      visibility: public
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
  register: coreos_images

- name: Include image tasks
  ansible.builtin.include_tasks: images.yml
  when: coreos_images.images | length == 0

- name: Include COE template tasks
  ansible.builtin.include_tasks: coe_templates.yml
