# Create the default project environments
---
- name: "Create the 'prod' project"
  openstack.cloud.project:
    state: present
    name: prod
    description: Production environment
    enabled: true
    domain_id: Default
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
  register: openstack_prod_project

- name: "Assign roles for the 'prod' project"
  openstack.cloud.role_assignment:
    user: admin
    role: admin
    project: prod
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: "Set quotas for the 'prod' project"
  openstack.cloud.quota:
    name: prod
    cloud: kolla-admin
    volumes: 25
    snapshots: 25
    gigabytes: -1
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: "Create the 'staging' project"
  openstack.cloud.project:
    state: present
    name: staging
    description: Staging environment
    enabled: true
    domain_id: Default
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: "Assign roles for the 'staging' project"
  openstack.cloud.role_assignment:
    user: admin
    role: admin
    project: staging
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: "Set quotas for the 'staging' project"
  openstack.cloud.quota:
    name: staging
    cloud: kolla-admin
    volumes: 25
    snapshots: 25
    gigabytes: -1
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: "Create the 'dev' project"
  openstack.cloud.project:
    state: present
    name: dev
    description: Development environment
    enabled: true
    domain_id: Default
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: "Assign roles for the 'dev' project"
  openstack.cloud.role_assignment:
    user: admin
    role: admin
    project: dev
    cloud: kolla-admin
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml

- name: "Set quotas for the 'dev' project"
  openstack.cloud.quota:
    name: dev
    cloud: kolla-admin
    volumes: 25
    snapshots: 25
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/kolla/clouds.yaml
