---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secrets
  namespace: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: radarr-secrets
    creationPolicy: Owner
  # Vault secret object
  data:
    - secretKey: apiKey
      remoteRef:
        key: /mediasrv/radarr
        property: apiKey
    - secretKey: sabnzbd-api-password
      remoteRef:
        key: /mediasrv/sabnzbd
        property: apiKey
