---
- name: Create the config override directory
  ansible.builtin.file:
    path: "{{ cinder_kolla_config_dir }}"
    state: directory
    mode: '0750'

- name: Template the 'cinder-api.conf' override file
  ansible.builtin.template:
    src: cinder-api.conf.j2
    dest: "{{ cinder_kolla_config_dir }}/cinder-api.conf"
    mode: '0640'
  notify: restart_containers
