---
- name: Set Python interpreter to venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ designate_kolla_venv }}/bin/python"

- name: Include record creation tasks
  ansible.builtin.include_tasks: create-records.yml

- name: Include recursive resolver tasks
  ansible.builtin.include_tasks: enable-recursion.yml
  when: designate_enable_recursion
