---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-operator
spec:
  targetNamespace: vault
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/workloads/platform/vault-operator/manifests
  prune: true
  wait: true
