---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr-secrets
  namespace: media-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  # Kubernetes secret object
  target:
    name: jellyseerr-secrets
    creationPolicy: Owner
  # Vault secret object
  data:
    - secretKey: jellyfin-server-id
      remoteRef:
        key: /mediasrv/jellyfin
        property: serverID
    - secretKey: radarr-api-key
      remoteRef:
        key: /mediasrv/radarr
        property: apiKey
    - secretKey: sonarr-api-key
      remoteRef:
        key: /mediasrv/sonarr
        property: apiKey
