---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: databases
  namespace: flux-system
spec:
  dependsOn:
    - name: postgres-operator
  interval: 60m
  path: ./cluster/apps/databases
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      GCP_BACKUP_PROJECT_ID: ${GCP_BACKUP_PROJECT_ID}
      GCP_BACKUP_BUCKET_NAME: ${GCP_BACKUP_BUCKET_NAME}
      GCP_BACKUP_BUCKET_CREDS: ${GCP_BACKUP_BUCKET_CREDS}
      BACKUP_REPO_PASSWORD: ${BACKUP_REPO_PASSWORD}
