---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: smart-home
  namespace: flux-system
spec:
  dependsOn:
    - name: csi-cinder
    - name: external-secrets
    - name: ingress-nginx
    - name: trust-manager
    - name: vault
    - name: volsync
  interval: 60m
  path: ./cluster/apps/smart-home
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      DOMAIN: ${DOMAIN}
      GCP_BACKUP_PROJECT_ID: ${GCP_BACKUP_PROJECT_ID}
      GCP_BACKUP_BUCKET_NAME: ${GCP_BACKUP_BUCKET_NAME}
      GCP_BACKUP_BUCKET_CREDS: ${GCP_BACKUP_BUCKET_CREDS}
      BACKUP_REPO_PASSWORD: ${BACKUP_REPO_PASSWORD}
